### ISSUE TITLE
Update module to support "Specialized" installation - multiple namespace

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-db2wh#8]
update the module to support the "Specialized" installation which will refer the common-services, cpd-opertors and cpd-instances namespace in the openshift

**Comment by triceam** [comment]
The module should not need any updates, as long as it is deployed into a namespace managed by CP4D

**Comment by balasgit** [comment]
For special installation (as per docs), Module requires update to operand operator before deploying DB2WH subscription. This is special case which needs to run as job on pod..

- https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=tasks-creating-operator-subscriptions#preinstall-operator-subscriptions__svc-subcrip

<img width="1211" alt="Screen Shot 2022-05-12 at 9 46 43 AM" src="https://user-images.githubusercontent.com/25986944/168102879-b3693678-9c7f-4b71-b461-2ac1262679fe.png">
tions

This applies to all CP4D service if they go with special installation as I discussed with Sasi / Snehal. Hence created ticket. 

Note: Above steps not required if its deployed in the single namespace such as express installation..

**Comment by balasgit** [comment]
Trying to test the DB2WH modules as CP4D instance is permanently installed on CP4D - https://gsicsi.slack.com/archives/C02KB99P2JC/p1652321657937489

Running into Secondary Rate limit error as modules are not working https://ibm-cloud.slack.com/archives/C02KB99P2JC/p1652370651738649

**Comment by balasgit** [comment]
Running into CP4D DB2WH instance creation issue - https://ibm-cloudplatform.slack.com/archives/C02KB99P2JC/p1652407382477529

Working with team to resolve the pull secret issues

**Comment by balasgit** [comment]
- Tried the pull secret updates in each namespace which didn't help. 

- As per team direction, there is separate module will be created for global pull secret. https://ibm-cloudplatform.slack.com/archives/C02KB99P2JC/p1652764350819179

**Comment by triceam** [comment]
@balasgit see the slack thread from last night.  I was able to get it to pass tests after setting the global pull secret on the clutser, and commenting out the individual pull secrets

**Comment by balasgit** [comment]
thanks Andy
